# 风化时间,单位天，默认7天
WEATHERING_TIME: 7

#活跃活动标志列表，默认1,2
ACTIVE_FLAG_LIST:
  - 1
  - 2

#MCA 文件目录
MCA_DIR: "/opt/MinecraftServer-AHA/survival/world/region"

#是否启用数据库模式，默认false:
#false Coreprotect-DataBase
#true CoreProtect-API
ENABLE_DATABASE: false

#如果是数据库请填写数据库信息
DATABASE:
  host: localhost
  port: 3306
  database: coreprotect
  username: root
  password: root
  table: co_block
