name: Weathering
version: '${project.version}'
main: cc.ahaly.weathering.Weathering
api-version: '1.21'
depend: [CoreProtect]
softdepend: [dynmap]
website: https://github.com/LIU-LIU-LIU/weathering
description: 使用 CoreProtect 和可选的 Dynmap 处理风化的插件。

permissions:
  weathering.use:
    description: "Weathering插件的默认权限"
    default: true
    children:
      weathering.query: true
  weathering.admin:
    description: "Weathering插件的op权限"
    default: op
    children:
      weathering.list: true
      weathering.draw: true
      weathering.reset: true
      weathering.remind: true

commands:
  weathering:
    description: Weathering 插件的主命令
    usage: /<command> <query|list|draw|reset|remind>
    aliases: [wth]
    permission: weathering.use
    tab-completer: cc.ahaly.weathering.WeatheringTabCompleter
  weathering.query:
    description: 查询区块状态
    usage: /weathering query
    permission: weathering.query
  weathering.list:
    description: 列出所有相关的区块
    usage: /weathering list
    permission: weathering.list
  weathering.draw:
    description: 绘制区块的相关信息
    usage: /weathering draw
    permission: weathering.draw
  weathering.reset:
    description: 重置区块
    usage: /weathering reset
    permission: weathering.reset
  weathering.remind:
    description: 提醒有关区块的信息
    usage: /weathering remind
    permission: weathering.remind