name: Weathering
version: '${project.version}'
main: cc.ahaly.weathering.Weathering
api-version: '1.21'
depend: [CoreProtect]
softdepend: [dynmap]
description: A plugin to handle weathering using CoreProtect and optionally Dynmap.
commands:
  weathering:
    description: Main command for the Weathering plugin
    usage: /<command> <query|list|draw>
    aliases: [wth]
    permission: weathering.use
permissions:
  weathering.use:
    description: Allows the use of the Weathering plugin commands
    default: op