name: Weathering
version: '${project.version}'
main: cc.ahaly.weathering.Weathering
api-version: '1.21'
depend: [CoreProtect]
softdepend: [dynmap]
description: A plugin to handle weathering using CoreProtect and optionally Dynmap.
commands:
  queryEvents:
    description: Queries MCA files for player events.
  drawRegions:
    description: Draws regions on Dynmap based on player events.